### ISSUE TITLE
Not enforcing the pattern for countries other than US

### ISSUE THREAD

**Issue by buddyackerman** [Bluefieldscom/intl-tel-input#272]
When the country is set to US the typed input is masked according to the placeholder pattern and it won't allow entering any more digits that the pattern allows.  This is only working for the US.  All other countries allow the entry of as many digits as the control will allow and the do not fill in accordance with the placeholder pattern.  I don't know if this is a problem with the plugin or the libphonenumber.js utility.  In the images below the first one shows the control with only the placeholder text and the second image shows it will data typed in.

![de_phonevalidation-1](https://cloud.githubusercontent.com/assets/8039125/9410330/4b7fadfa-47e5-11e5-84e1-9d1d0bf58fd3.PNG)

![de_phonevalidation-2](https://cloud.githubusercontent.com/assets/8039125/9410335/53e15a98-47e5-11e5-9fe3-873a7000636d.PNG)

**Comment by jackocnr** [comment]
Please make sure you're using the latest version. See the [demo page](jackocnr.com/intl-tel-input.html)

**Comment by buddyackerman** [comment]
That link doesn't work

**Comment by jackocnr** [comment]
Fixed

**Comment by buddyackerman** [comment]
It's actually worse now.  I downloaded the latest version (6.06) and got the latest flags.png and now the flag is wrong and it still doesn't enforce the pattern nor does it format the entry if it's not US.  Also, utils.js doesn't enforce the number limit for US like the libphonenumber.js does so if you type more than 10 digits for a US phone number it just keeps going where as the libphonenumber.js will not accept anymore digits (although it will allow them for other countries).  The demo page exhibits this behavior as well however, the flags work.

**Comment by jackocnr** [comment]
If your flag is wrong that most likely means you need to update your CSS.

And no, we don't enforce number lengths any more because it was hacky - you can search the issues for more info.

Is formatting working now?

**Comment by buddyackerman** [comment]
The formatting doesn't work not even on your demo page.  Go to your demo page and select Germany as the country and type in a valid number.  If you type in a valid number it's just left as a string of number, unformatted.

I downloaded the new CSS and it's worse now it shows a gray box where the flag is supposed to be.

These tests are being done in Chrome.

**Comment by jackocnr** [comment]
Re: demo page, if I type the example number from the placeholder (01512 3456789) the formatting works - it adds that space in the middle. What number are you trying, what do you expect to get, and what do you actually get?

**Comment by buddyackerman** [comment]
On the demo page if I type just the right set of number then it formats it (same in my application although the German placeholder is quite a different format).  I have no idea what are valid phone numbers in Germany so I don't really know what to type.  For US, it will format ANY random numbers, it's might not validate but it still formats any set of 10 digits.

**Comment by jackocnr** [comment]
OK, so what exactly is the problem?

On Fri, 21 Aug 2015 12:41 pm buddyackerman <notifications@github.com> wrote:

> On the demo page if I type just the right set of number then it formats it
> (same in my application although the German placeholder is quite a
> different format). I have no idea what are valid phone numbers in Germany
> so I don't really know what to type. For US, it will format ANY random
> numbers, it's might not validate but it still formats any set of 10 digits.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bluefieldscom/intl-tel-input/issues/272#issuecomment-133539855>
> .
>
-- 
Jack O'Connor - Mitoo

**Comment by lepipele** [comment]
@buddyackerman @jackocnr If I may chime in I think this is the problem:

If phone number is invalid you won't format it. So in US try entering for example +1800 23142354435

As soon as you go over 7 digits for local phone number formatting will be lost.

In German if you enter valid number (01512 1234567 for example) formatting will be there... for invalid numbers like 1111111111111 there won't be any formatting.

**Comment by buddyackerman** [comment]
Go to the validation demo page and with the set to US type ten 5's into the box.  It fails validation but it still formats it. Clear the box and change the country to Germany and type the same ten 5's.  It validates but it doesn't format it.  It should format ANYTHING that fits within the length limits of that country regardless of whether it validates or not.  When it's set to US it does this, it doesn't for other countries (at least the handful I tested).

**Comment by buddyackerman** [comment]
lepipele, format and validation are completely separate operations.  They should not depend on each other.  The US format and validation seem to work correctly, it formats any set of ten number even if they don't validate.  If you use the libphonenumber.js instead of the customized utils.js it will even restrict the number to the first ten digits that you type.

**Comment by lepipele** [comment]
@buddyackerman this is what I see... if you enter 555 555 5555 - with +1 that's valid US number:

![01](https://cloud.githubusercontent.com/assets/5191402/9418270/637e90fa-4818-11e5-9618-6218469dd6d7.png)

Now if I enter another 5 - it's invalid number and formatting goes away:

![02](https://cloud.githubusercontent.com/assets/5191402/9418278/6ff91a9e-4818-11e5-8bd1-0b1e3940cea1.png)

If I go back to ten 5s and switch to german, this is what I see:

![03](https://cloud.githubusercontent.com/assets/5191402/9418292/7eb32c64-4818-11e5-8440-1a7e6839f2ca.png)

But if I add 0 in front making it valid number, there is some formatting:

![04](https://cloud.githubusercontent.com/assets/5191402/9418300/88d5de58-4818-11e5-8485-00acd90a8f21.png)

...

To conclude - I actually agree that this needs improvement. But you won't get improvement by arguing and yelling at people with shoulda, woulda, coulda. Fix it yourself if it bothers you that much - I would welcome pull request on this topic.

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber)'s AsYouTypeFormatter for all formatting, so if you have any issues/suggestions you should speak to them.

**Comment by buddyackerman** [comment]
@lepipele, ten 5's in not a valid US number.  Go the the validation demo page and enter it, it will show you that it's not valid as there is no 555 area code in the US.  Ten 5's is not a valid number but it still gets formatted correctly.  In fact you can type ANY ten numbers when US is selected and it will format it (try all zeros).

**Comment by lepipele** [comment]
@buddyackerman Hey man - do you really have so much free time to argue with me here about phone number formats? :)

I tried to help - sorry if I failed. Enjoy your day (wave)

**Comment by buddyackerman** [comment]
Since the real problem is the AsYouTypeFormatter, I posted the issue with the libphonenumber group and the issue had already been raised and the solution is to type a "+" to start with and that will get the formatter working correctly.
